import type { MetricDefinition } from '@carparty/types';

export const defaultMetrics: MetricDefinition[] = [
  {
    key: 'sales.count',
    label: 'Количество продаж',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'bar',
    module: 'SALES',
  },
  {
    key: 'sales.revenue',
    label: 'Выручка от продаж',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'area',
    module: 'SALES',
  },
  {
    key: 'listing.views',
    label: 'Просмотры объявлений',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['listing_id', 'source'],
    chartType: 'line',
    module: 'SALES',
  },
  {
    key: 'listing.clicks',
    label: 'Клики',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['listing_id', 'target'],
    chartType: 'line',
    module: 'SALES',
  },
  {
    key: 'listing.conversion',
    label: 'Конверсия просмотров',
    type: 'rate',
    aggregation: 'avg',
    chartType: 'number',
    module: 'SALES',
  },
  {
    key: 'import.completed',
    label: 'Завершённые пригоны',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'IMPORT',
  },
  {
    key: 'import.in_progress',
    label: 'Пригоны в работе',
    type: 'gauge',
    aggregation: 'count',
    chartType: 'number',
    module: 'IMPORT',
  },
  {
    key: 'parts.sold',
    label: 'Запчасти проданы',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'bar',
    module: 'DISMANTLE',
  },
  {
    key: 'parts.views',
    label: 'Просмотры запчастей',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['part_id', 'category'],
    chartType: 'line',
    module: 'DISMANTLE',
  },
  {
    key: 'service.orders',
    label: 'Заказ-наряды',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'SERVICE',
  },
  {
    key: 'service.revenue',
    label: 'Выручка сервиса',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'area',
    module: 'SERVICE',
  },
  {
    key: 'clients.new',
    label: 'Новые клиенты',
    type: 'counter',
    aggregation: 'count',
    chartType: 'line',
    module: 'global',
  },
  {
    key: 'leads.total',
    label: 'Все заявки',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'global',
  },
];
