import type { MetricDefinition } from '@carparty/types';

export const defaultMetrics: MetricDefinition[] = [
  {
    key: 'sales.count',
    label: 'Количество продаж',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'bar',
    module: 'SALES',
  },
  {
    key: 'sales.revenue',
    label: 'Выручка от продаж',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'area',
    module: 'SALES',
  },
  {
    key: 'listing.views',
    label: 'Просмотры объявлений',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['listing_id', 'source'],
    chartType: 'line',
    module: 'SALES',
  },
  {
    key: 'listing.clicks',
    label: 'Клики',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['listing_id', 'target'],
    chartType: 'line',
    module: 'SALES',
  },
  {
    key: 'listing.conversion',
    label: 'Конверсия просмотров',
    type: 'rate',
    aggregation: 'avg',
    chartType: 'number',
    module: 'SALES',
  },
  {
    key: 'import.completed',
    label: 'Завершённые пригоны',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'IMPORT',
  },
  {
    key: 'import.in_progress',
    label: 'Пригоны в работе',
    type: 'gauge',
    aggregation: 'count',
    chartType: 'number',
    module: 'IMPORT',
  },
  {
    key: 'parts.sold',
    label: 'Запчасти проданы',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'bar',
    module: 'DISMANTLE',
  },
  {
    key: 'parts.views',
    label: 'Просмотры запчастей',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['part_id', 'category'],
    chartType: 'line',
    module: 'DISMANTLE',
  },
  {
    key: 'service.orders',
    label: 'Заказ-наряды',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'SERVICE',
  },
  {
    key: 'service.revenue',
    label: 'Выручка сервиса',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'area',
    module: 'SERVICE',
  },
  {
    key: 'clients.new',
    label: 'Новые клиенты',
    type: 'counter',
    aggregation: 'count',
    chartType: 'line',
    module: 'global',
  },
  {
    key: 'leads.total',
    label: 'Все заявки',
    type: 'counter',
    aggregation: 'count',
    chartType: 'bar',
    module: 'global',
  },
  {
    key: 'leads.ingested',
    label: 'Собранные объявления',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['source', 'outcome'],
    chartType: 'bar',
    module: 'SALES',
  },
  {
    key: 'leads.promoted',
    label: 'Продвинутые в CRM',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['source'],
    chartType: 'line',
    module: 'SALES',
  },
  {
    key: 'sales.telegram_leads',
    label: 'Лиды из Telegram',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['channel_id'],
    chartType: 'bar',
    module: 'SALES',
  },
  {
    key: 'bot.deliveries',
    label: 'Доставки бота',
    type: 'counter',
    aggregation: 'sum',
    chartType: 'area',
    module: 'global',
  },
  {
    key: 'bot.payments',
    label: 'Оплаты подписки',
    type: 'counter',
    aggregation: 'count',
    dimensions: ['plan'],
    chartType: 'bar',
    module: 'global',
  },
  {
    key: 'bot.revenue',
    label: 'Выручка бота (UAH)',
    type: 'counter',
    aggregation: 'sum',
    dimensions: ['plan'],
    chartType: 'area',
    module: 'global',
  },
  {
    key: 'bot.subscribers.new',
    label: 'Новые подписчики бота',
    type: 'counter',
    aggregation: 'count',
    chartType: 'line',
    module: 'global',
  },
  {
    key: 'admin.daily.leads',
    label: 'Лиды за день',
    type: 'gauge',
    aggregation: 'sum',
    dimensions: ['day'],
    chartType: 'line',
    module: 'global',
  },
  {
    key: 'admin.daily.deliveries',
    label: 'Доставки за день',
    type: 'gauge',
    aggregation: 'sum',
    dimensions: ['day'],
    chartType: 'line',
    module: 'global',
  },
  {
    key: 'admin.daily.revenue',
    label: 'Выручка за день',
    type: 'gauge',
    aggregation: 'sum',
    dimensions: ['day'],
    chartType: 'area',
    module: 'global',
  },
];
